# Jekyll configuration
markdown: kramdown
highlighter: rouge
paginate: 100 # it will paginate after this number
language: 'en-uk'
words_per_minute: 200

# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: /
baseurl_fix: /

# Website info
title: artificial::mind
description: Thoughts about Graphics, C++, Optimization, and more
cover: assets/images/blog-cover.jpg
logo: assets/images/title-logo-alpha.png
logo_dark: assets/images/favicon.png
favicon: assets/images/favicon.png
production_url: https://artificial-mind.net/
source_url: https://github.com/Philip-Trettner/Philip-Trettner.github.io
CNAME: artificial-mind.net #add cname for website to be created

# Social info
navigation: True # show the navbar links
subscribers: False # you need to connect an external service for this to work,
# if 'True' the submit button is disabled for now, but you can change that
# by editing `_includes/subscribe-form.html`
twitter: PhilipTrettner # replace by your username
facebook: philip.trettner # replace by your username
github: Philip-Trettner

# Disqus
disqus: False
disqus_shortname: jekyller # replace with your disqus username

# Google Analytics
# google_analytics: UA-69281367-1 # replace with your GA tracking identifier

# Permalinks
permalink: /blog/:year/:month/:day/:title
# permalink: /author/:author
# permalink: /tag/:tag

# Authors' info in `_data/authors.yml`
# Tags' info in `_data/tags_info.yml`

# gems and other configs
plugins_dir: [_plugins]
plugins: [jekyll-paginate, jekyll-feed]

feed:
  path: feed.xml

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...

# Settings for builing master branch with travis-ci
# with jekyll-travis

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
safe: False
lsi: False
username: Philip-Trettner
repo: Philip-Trettner.github.io
branch: master
relative_source: .
destination: _site
production_url: https://artificial-mind.net/
source_url: https://github.com/Philip-Trettner/Philip-Trettner.github.io

exclude:
  - assets/css
  - node_modules
  - vendor
  - .travis.yml
  - Gemfile
  - Gemfile.lock
  - GHOST.txt
  - gulpfile.js
  - LICENSE
  - package.json
  - Rakefile
  - README.md
  - script.py
  - changelog.md
  - "*.Rmd"
  - .git*
